apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentd
  namespace: logging
spec:
  interval: 5m
  chart:
    spec:
      chart: fluentd
      version: 0.5.2 
      sourceRef:
        kind: HelmRepository
        name: fluentd
        namespace: flux-system
  values:
    config:
      output:
        type: elasticsearch
        elasticsearch:
          host: "elasticsearch-master.logging.svc.cluster.local"  
          port: 9200
