apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  releaseName: loki
  interval: 1m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: monitoring
  values:
    loki:
      config:
        table_manager:
          retention_deletes_enabled: true
    persistence:
      enabled: false  
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 400Mi
