apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 6.12.0
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: monitoring
  values:
    loki:
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: 2020-10-24
            store: boltdb
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 168h
      storage_config:
        boltdb:
          directory: /tmp/loki/boltdb
        filesystem:
          directory: /tmp/loki/chunks
      limits_config:
        enforce_metric_name: false
    persistence:
      enabled: false 
    singleBinary: true 
