apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argocd-apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./Devops/argo-applications
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
