apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}-pdb
  namespace: {{ .Values.env }}
spec:
  minAvailable: {{ .Values.minAvailable }} #maxUnavailable mentions how many pods will be terminated 
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
