apiVersion: v1
kind: Service
metadata:
  name: postgresql-headless
  labels:
    app: postgresql
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.postgresql.port }}
  clusterIP: None
  selector:
    app: postgresql
