apiVersion: apps/v1
kind: Deployment
metadata:
  name: plivo-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: plivo-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: plivo-frontend
    spec:
      containers:
        - name: plivo-frontend
          image: harsha3330/plivo-frontend:main-3-date-20240929-071012
          ports:
            - containerPort: 3000

