apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal-communication
  namespace: applications
spec:
  podSelector: {}  
  policyTypes:
  - Ingress  
  ingress:
  - from:
    - podSelector: {}