apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
spec:
  interval: 5m
  chart:
    spec:
      chart: elasticsearch
      version: 7.17.0 
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    replicas: 2
    resources:
      requests:
        memory: 1Gi
        cpu: 100m
    service:
      type: ClusterIP
