apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
spec:
  releaseName: elasticsearch
  chart:
    spec:
      chart: elasticsearch
      version: 8.5.1 
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: logging
  values:
    minimumMasterNodes: 2
    master:
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          cpu: 500m
          memory: 2Gi
    data:
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          cpu: 500m
          memory: 2Gi
    http:
      service:
        enabled: true
        type: ClusterIP
